// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package hu.iboard.coandco.datamagic.vo.others;

import java.util.List;

/**
 * 
 */
public class FilesVO implements java.io.Serializable
{
 
    /**
	 * 
	 */
	private static final long serialVersionUID = 8586567083290009385L;

	public FilesVO(java.lang.Long id, java.lang.String name, byte[] file, java.lang.Long fileTypeId, java.lang.Long size, java.sql.Timestamp uploadDate, java.lang.String plainText, java.lang.Long userId, List resultDetails, java.lang.Integer hitCount, java.lang.String MimeType, java.lang.String fileTypeValue)
    {
        this.id = id;
        this.name = name;
        this.file = file;
        this.fileTypeId = fileTypeId;
        this.size = size;
        this.uploadDate = uploadDate;
        this.plainText = plainText;
        this.userId = userId;
        this.resultDetails = resultDetails;
        this.hitCount = hitCount;
        this.MimeType = MimeType;
        this.fileTypeValue = fileTypeValue;
    }

    private java.lang.Long id;

    /**
     * 
     */
    public java.lang.Long getId()
    {
        return this.id;
    }

    public void setId(java.lang.Long id)
    {
        this.id = id;
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private byte[] file;

    /**
     * 
     */
    public byte[] getFile()
    {
        return this.file;
    }

    public void setFile(byte[] file)
    {
        this.file = file;
    }

    private java.lang.Long fileTypeId;

    /**
     * 
     */
    public java.lang.Long getFileTypeId()
    {
        return this.fileTypeId;
    }

    public void setFileTypeId(java.lang.Long fileTypeId)
    {
        this.fileTypeId = fileTypeId;
    }

    private java.lang.Long size;

    /**
     * 
     */
    public java.lang.Long getSize()
    {
        return this.size;
    }

    public void setSize(java.lang.Long size)
    {
        this.size = size;
    }

    private java.sql.Timestamp uploadDate;

    /**
     * 
     */
    public java.sql.Timestamp getUploadDate()
    {
        return this.uploadDate;
    }

    public void setUploadDate(java.sql.Timestamp uploadDate)
    {
        this.uploadDate = uploadDate;
    }

    private java.lang.String plainText;

    /**
     * 
     */
    public java.lang.String getPlainText()
    {
        return this.plainText;
    }

    public void setPlainText(java.lang.String plainText)
    {
        this.plainText = plainText;
    }

    private java.lang.Long userId;

    /**
     * 
     */
    public java.lang.Long getUserId()
    {
        return this.userId;
    }

    public void setUserId(java.lang.Long userId)
    {
        this.userId = userId;
    }

    private java.util.List resultDetails;

    /**
     * 
     */
    public java.util.List getResultDetails()
    {
        return this.resultDetails;
    }

    public void setResultDetails(java.util.List resultDetails)
    {
        this.resultDetails = resultDetails;
    }

    private java.lang.Integer hitCount;

    /**
     * 
     */
    public java.lang.Integer getHitCount()
    {
        return this.hitCount;
    }

    public void setHitCount(java.lang.Integer hitCount)
    {
        this.hitCount = hitCount;
    }

    private java.lang.String MimeType;

    /**
     * 
     */
    public java.lang.String getMimeType()
    {
        return this.MimeType;
    }

    public void setMimeType(java.lang.String MimeType)
    {
        this.MimeType = MimeType;
    }

    private java.lang.String fileTypeValue;

    /**
     * 
     */
    public java.lang.String getFileTypeValue()
    {
        return this.fileTypeValue;
    }

    public void setFileTypeValue(java.lang.String fileTypeValue)
    {
        this.fileTypeValue = fileTypeValue;
    }

}