
package hu.iboard.coandco.datamagic.webservice.managementreport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DMRPC", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://ftp.datamagic.hu:7532/DMRPC?wsdl")
public class DMRPC
    extends Service
{

    private final static URL DMRPC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(hu.iboard.coandco.datamagic.webservice.managementreport.DMRPC.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = hu.iboard.coandco.datamagic.webservice.managementreport.DMRPC.class.getResource(".");
            url = new URL(baseUrl, "http://ftp.datamagic.hu:7532/DMRPC?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ftp.datamagic.hu:7532/DMRPC?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DMRPC_WSDL_LOCATION = url;
    }

    public DMRPC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMRPC() {
        super(DMRPC_WSDL_LOCATION, new QName("http://tempuri.org/", "DMRPC"));
    }

    /**
     * 
     * @return
     *     returns IDMRPCContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IDMRPC_Contract")
    public IDMRPCContract getBasicHttpBindingIDMRPCContract() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDMRPC_Contract"), IDMRPCContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDMRPCContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IDMRPC_Contract")
    public IDMRPCContract getBasicHttpBindingIDMRPCContract(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDMRPC_Contract"), IDMRPCContract.class, features);
    }

}
