
package hu.iboard.coandco.datamagic.webservice.managementreport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IDMRPC_Contract", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDMRPCContract {


    /**
     * 
     * @param sessionid
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetAruCount", action = "http://tempuri.org/IDMRPC_Contract/GetAruCount")
    @WebResult(name = "GetAruCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAruCount", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetAruCount")
    @ResponseWrapper(localName = "GetAruCountResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetAruCountResponse")
    public Integer getAruCount(
        @WebParam(name = "sessionid", targetNamespace = "http://tempuri.org/")
        Long sessionid);

    /**
     * 
     * @param sessionid
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetDateTimeNow", action = "http://tempuri.org/IDMRPC_Contract/GetDateTimeNow")
    @WebResult(name = "GetDateTimeNowResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDateTimeNow", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetDateTimeNow")
    @ResponseWrapper(localName = "GetDateTimeNowResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetDateTimeNowResponse")
    public XMLGregorianCalendar getDateTimeNow(
        @WebParam(name = "sessionid", targetNamespace = "http://tempuri.org/")
        Long sessionid);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLastException", action = "http://tempuri.org/IDMRPC_Contract/GetLastException")
    @WebResult(name = "GetLastExceptionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastException", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetLastException")
    @ResponseWrapper(localName = "GetLastExceptionResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetLastExceptionResponse")
    public String getLastException();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMachineName", action = "http://tempuri.org/IDMRPC_Contract/GetMachineName")
    @WebResult(name = "GetMachineNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMachineName", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetMachineName")
    @ResponseWrapper(localName = "GetMachineNameResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetMachineNameResponse")
    public String getMachineName();

    /**
     * 
     * @param cegUnikazon
     * @param dataBase
     * @param dbPass
     * @param dolgozoPass
     * @param dbUser
     * @param dbServer
     * @param dolgozoKod
     * @param dbPort
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetSessionId", action = "http://tempuri.org/IDMRPC_Contract/GetSessionId")
    @WebResult(name = "GetSessionIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSessionId", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetSessionId")
    @ResponseWrapper(localName = "GetSessionIdResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetSessionIdResponse")
    public Long getSessionId(
        @WebParam(name = "dbServer", targetNamespace = "http://tempuri.org/")
        String dbServer,
        @WebParam(name = "dbPort", targetNamespace = "http://tempuri.org/")
        String dbPort,
        @WebParam(name = "dbUser", targetNamespace = "http://tempuri.org/")
        String dbUser,
        @WebParam(name = "dbPass", targetNamespace = "http://tempuri.org/")
        String dbPass,
        @WebParam(name = "dataBase", targetNamespace = "http://tempuri.org/")
        String dataBase,
        @WebParam(name = "cegUnikazon", targetNamespace = "http://tempuri.org/")
        String cegUnikazon,
        @WebParam(name = "dolgozoKod", targetNamespace = "http://tempuri.org/")
        Integer dolgozoKod,
        @WebParam(name = "dolgozoPass", targetNamespace = "http://tempuri.org/")
        String dolgozoPass);

    /**
     * 
     * @param sessionid
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsValidSession", action = "http://tempuri.org/IDMRPC_Contract/IsValidSession")
    @WebResult(name = "IsValidSessionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsValidSession", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.IsValidSession")
    @ResponseWrapper(localName = "IsValidSessionResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.IsValidSessionResponse")
    public Boolean isValidSession(
        @WebParam(name = "sessionid", targetNamespace = "http://tempuri.org/")
        Long sessionid);

    /**
     * 
     * @param datum
     * @param sessionid
     * @return
     *     returns hu.iboard.coandco.datamagic.webservice.managementreport.ManagementReport
     */
    @WebMethod(operationName = "GetManagementReport", action = "http://tempuri.org/IDMRPC_Contract/GetManagementReport")
    @WebResult(name = "GetManagementReportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetManagementReport", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetManagementReport")
    @ResponseWrapper(localName = "GetManagementReportResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetManagementReportResponse")
    public ManagementReport getManagementReport(
        @WebParam(name = "sessionid", targetNamespace = "http://tempuri.org/")
        Long sessionid,
        @WebParam(name = "datum", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar datum);

    /**
     * 
     * @param gridid
     * @param columnindex
     * @param rowindex
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "GetGridValue", action = "http://tempuri.org/IDMRPC_Contract/GetGridValue")
    @WebResult(name = "GetGridValueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGridValue", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetGridValue")
    @ResponseWrapper(localName = "GetGridValueResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.GetGridValueResponse")
    public Object getGridValue(
        @WebParam(name = "gridid", targetNamespace = "http://tempuri.org/")
        Integer gridid,
        @WebParam(name = "rowindex", targetNamespace = "http://tempuri.org/")
        Integer rowindex,
        @WebParam(name = "columnindex", targetNamespace = "http://tempuri.org/")
        Integer columnindex);

    /**
     * 
     * @param message
     * @param gridid
     * @param gridDescriptor
     * @param endpoint
     */
    @WebMethod(operationName = "SendGrid", action = "http://tempuri.org/IDMRPC_Contract/SendGrid")
    @RequestWrapper(localName = "SendGrid", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.SendGrid")
    @ResponseWrapper(localName = "SendGridResponse", targetNamespace = "http://tempuri.org/", className = "hu.iboard.coandco.datamagic.webservice.managementreport.SendGridResponse")
    public void sendGrid(
        @WebParam(name = "endpoint", targetNamespace = "http://tempuri.org/")
        String endpoint,
        @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
        String message,
        @WebParam(name = "gridid", targetNamespace = "http://tempuri.org/")
        Integer gridid,
        @WebParam(name = "gridDescriptor", targetNamespace = "http://tempuri.org/")
        String gridDescriptor);

}
