package hu.iboard.coandco.datamagic.model.rendel;

// Generated Aug 11, 2009 4:42:50 PM by Hibernate Tools 3.2.4.GA

import hu.iboard.coandco.datamagic.model.rendtet.Rendtet;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rendel generated by hbm2java
 */
@Entity
@Table(name = "RENDEL")
public class Rendel implements java.io.Serializable {

	private static final long serialVersionUID = 4060879198549892811L;
	private String sorszam;
	private String sorsztipk;
	private String elotag;
	private Date kelt;
	private Date telj;
	private Date esedkelt;
	private String eladoszla;
	private String fizmod;
	private String szlaszam;
	private String devnem;
	private BigDecimal arfolyam;
	private boolean sztorno;
	private Date fizetve;
	private Integer tipus;
	private Integer peldany;
	private Integer vevokod;
	private String vnev;
	private String vvaros;
	private String vcim;
	private String virsz;
	private String vadoszam;
	private String vfolyszam;
	private BigDecimal kedvezm;
	private String munkszam;
	private Integer munkszuk;
	private String kiall;
	private Integer nyelv;
	private String megj;
	private BigDecimal engedm;
	private boolean konyv;
	private boolean elkuld;
	private String jobbala;
	private String jobbtit;
	private String balala;
	private String baltit;
	private BigDecimal bruttosuly;
	private BigDecimal colli;
	private Date rfizetve;
	private BigDecimal rossz;
	private String jovair;
	private Date vighatido;
	private String statusz;
	private String kivagybe;
	private BigDecimal netto;
	private BigDecimal brutto;
	private BigDecimal dnetto;
	private BigDecimal dbrutto;
	private String alapbizt;
	private String fuvmod;
	private String atvhely;
	private String sirsz;
	private String svaros;
	private String scim;
	private String stelefon;
	private String vfax;
	private String swiftcode;
	private String vorszag;
	private String vkapcstart;
	private String megrazon;
	private String kozadoszam;
	private Integer ugyint;
	private Date vfizdat;
	private boolean megjfile;
	private String iban;
	private String vkozadosz;
	private BigDecimal nettosuly;
	private String kamionjel;
	private boolean kulrend;
	private Integer estat;
	private String iktatoszam;
	private String vkapcstel;
	private String elolegssz;
	private boolean betudva;
	private BigDecimal elolegert;
	private boolean isjavit;
	private boolean garis;
	private boolean kgyub;
	private boolean csere;
	private boolean szazas;
	private Integer brndid;
	private Integer modkod;
	private Date moddatum;
	private Integer behozta;
	private boolean mindenok;
	private Date mindokdat;
	private Integer labszerv;
	private String venyvonal;
	private boolean ajanlatot;
	private boolean venyes;
	private boolean moregari;
	private Integer javkarb;
	private boolean reklamacio;
	private Date insdatum;
	private Integer inskod;
	private boolean modizva;
	private boolean kerdeses;
	private Integer status;
	private String deviza;
	private String bnokod;
	private Boolean gyseBe;
	private Integer dimenztio1;
	private Date vfelirdat;
	private String snev;
	private Boolean csakub;
	private String vonalkod;
	private Integer fuvar;
	private Integer lefejto;
	private Integer szlaprofil;
	private Integer lakosvevo;

	private Set<Rendtet> rendtets = new HashSet<Rendtet>(0);

	public Rendel() {
	}

	public Rendel(String sorszam) {
		this.sorszam = sorszam;
	}

	@Id
	@Column(name = "SORSZAM", unique = true, nullable = false, length = 15)
	public String getSorszam() {
		return this.sorszam;
	}

	public void setSorszam(String sorszam) {
		this.sorszam = sorszam;
	}

	@Column(name = "SORSZTIPK", length = 1)
	public String getSorsztipk() {
		return this.sorsztipk;
	}

	public void setSorsztipk(String sorsztipk) {
		this.sorsztipk = sorsztipk;
	}

	@Column(name = "ELOTAG", length = 10)
	public String getElotag() {
		return this.elotag;
	}

	public void setElotag(String elotag) {
		this.elotag = elotag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "KELT", length = 19)
	public Date getKelt() {
		return this.kelt;
	}

	public void setKelt(Date kelt) {
		this.kelt = kelt;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "TELJ", length = 19)
	public Date getTelj() {
		return this.telj;
	}

	public void setTelj(Date telj) {
		this.telj = telj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ESEDKELT", length = 19)
	public Date getEsedkelt() {
		return this.esedkelt;
	}

	public void setEsedkelt(Date esedkelt) {
		this.esedkelt = esedkelt;
	}

	@Column(name = "ELADOSZLA", length = 26)
	public String getEladoszla() {
		return this.eladoszla;
	}

	public void setEladoszla(String eladoszla) {
		this.eladoszla = eladoszla;
	}

	@Column(name = "FIZMOD", length = 11)
	public String getFizmod() {
		return this.fizmod;
	}

	public void setFizmod(String fizmod) {
		this.fizmod = fizmod;
	}

	@Column(name = "SZLASZAM", length = 26)
	public String getSzlaszam() {
		return this.szlaszam;
	}

	public void setSzlaszam(String szlaszam) {
		this.szlaszam = szlaszam;
	}

	@Column(name = "DEVNEM", length = 4)
	public String getDevnem() {
		return this.devnem;
	}

	public void setDevnem(String devnem) {
		this.devnem = devnem;
	}

	@Column(name = "ARFOLYAM")
	public BigDecimal getArfolyam() {
		return this.arfolyam;
	}

	public void setArfolyam(BigDecimal arfolyam) {
		this.arfolyam = arfolyam;
	}

	@Column(name = "SZTORNO")
	public boolean isSztorno() {
		return this.sztorno;
	}

	public void setSztorno(boolean sztorno) {
		this.sztorno = sztorno;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "FIZETVE", length = 19)
	public Date getFizetve() {
		return this.fizetve;
	}

	public void setFizetve(Date fizetve) {
		this.fizetve = fizetve;
	}

	@Column(name = "TIPUS")
	public Integer getTipus() {
		return this.tipus;
	}

	public void setTipus(Integer tipus) {
		this.tipus = tipus;
	}

	@Column(name = "PELDANY")
	public Integer getPeldany() {
		return this.peldany;
	}

	public void setPeldany(Integer peldany) {
		this.peldany = peldany;
	}

	@Column(name = "VEVOKOD")
	public Integer getVevokod() {
		return this.vevokod;
	}

	public void setVevokod(Integer vevokod) {
		this.vevokod = vevokod;
	}

	@Column(name = "VNEV", length = 50)
	public String getVnev() {
		return this.vnev;
	}

	public void setVnev(String vnev) {
		this.vnev = vnev;
	}

	@Column(name = "VVAROS", length = 25)
	public String getVvaros() {
		return this.vvaros;
	}

	public void setVvaros(String vvaros) {
		this.vvaros = vvaros;
	}

	@Column(name = "VCIM", length = 50)
	public String getVcim() {
		return this.vcim;
	}

	public void setVcim(String vcim) {
		this.vcim = vcim;
	}

	@Column(name = "VIRSZ", length = 10)
	public String getVirsz() {
		return this.virsz;
	}

	public void setVirsz(String virsz) {
		this.virsz = virsz;
	}

	@Column(name = "VADOSZAM", length = 13)
	public String getVadoszam() {
		return this.vadoszam;
	}

	public void setVadoszam(String vadoszam) {
		this.vadoszam = vadoszam;
	}

	@Column(name = "VFOLYSZAM", length = 8)
	public String getVfolyszam() {
		return this.vfolyszam;
	}

	public void setVfolyszam(String vfolyszam) {
		this.vfolyszam = vfolyszam;
	}

	@Column(name = "KEDVEZM", precision = 11, scale = 1)
	public BigDecimal getKedvezm() {
		return this.kedvezm;
	}

	public void setKedvezm(BigDecimal kedvezm) {
		this.kedvezm = kedvezm;
	}

	@Column(name = "MUNKSZAM", length = 50)
	public String getMunkszam() {
		return this.munkszam;
	}

	public void setMunkszam(String munkszam) {
		this.munkszam = munkszam;
	}

	@Column(name = "MUNKSZUK")
	public Integer getMunkszuk() {
		return this.munkszuk;
	}

	public void setMunkszuk(Integer munkszuk) {
		this.munkszuk = munkszuk;
	}

	@Column(name = "KIALL", length = 30)
	public String getKiall() {
		return this.kiall;
	}

	public void setKiall(String kiall) {
		this.kiall = kiall;
	}

	@Column(name = "NYELV")
	public Integer getNyelv() {
		return this.nyelv;
	}

	public void setNyelv(Integer nyelv) {
		this.nyelv = nyelv;
	}

	@Column(name = "MEGJ", length = 100)
	public String getMegj() {
		return this.megj;
	}

	public void setMegj(String megj) {
		this.megj = megj;
	}

	@Column(name = "ENGEDM")
	public BigDecimal getEngedm() {
		return this.engedm;
	}

	public void setEngedm(BigDecimal engedm) {
		this.engedm = engedm;
	}

	@Column(name = "KONYV")
	public boolean isKonyv() {
		return this.konyv;
	}

	public void setKonyv(boolean konyv) {
		this.konyv = konyv;
	}

	@Column(name = "ELKULD")
	public boolean isElkuld() {
		return this.elkuld;
	}

	public void setElkuld(boolean elkuld) {
		this.elkuld = elkuld;
	}

	@Column(name = "JOBBALA", length = 30)
	public String getJobbala() {
		return this.jobbala;
	}

	public void setJobbala(String jobbala) {
		this.jobbala = jobbala;
	}

	@Column(name = "JOBBTIT", length = 30)
	public String getJobbtit() {
		return this.jobbtit;
	}

	public void setJobbtit(String jobbtit) {
		this.jobbtit = jobbtit;
	}

	@Column(name = "BALALA", length = 30)
	public String getBalala() {
		return this.balala;
	}

	public void setBalala(String balala) {
		this.balala = balala;
	}

	@Column(name = "BALTIT", length = 30)
	public String getBaltit() {
		return this.baltit;
	}

	public void setBaltit(String baltit) {
		this.baltit = baltit;
	}

	@Column(name = "BRUTTOSULY", precision = 17, scale = 3)
	public BigDecimal getBruttosuly() {
		return this.bruttosuly;
	}

	public void setBruttosuly(BigDecimal bruttosuly) {
		this.bruttosuly = bruttosuly;
	}

	@Column(name = "COLLI", precision = 17, scale = 3)
	public BigDecimal getColli() {
		return this.colli;
	}

	public void setColli(BigDecimal colli) {
		this.colli = colli;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "RFIZETVE", length = 19)
	public Date getRfizetve() {
		return this.rfizetve;
	}

	public void setRfizetve(Date rfizetve) {
		this.rfizetve = rfizetve;
	}

	@Column(name = "ROSSZ")
	public BigDecimal getRossz() {
		return this.rossz;
	}

	public void setRossz(BigDecimal rossz) {
		this.rossz = rossz;
	}

	@Column(name = "JOVAIR", length = 1)
	public String getJovair() {
		return this.jovair;
	}

	public void setJovair(String jovair) {
		this.jovair = jovair;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "VIGHATIDO", length = 19)
	public Date getVighatido() {
		return this.vighatido;
	}

	public void setVighatido(Date vighatido) {
		this.vighatido = vighatido;
	}

	@Column(name = "STATUSZ", length = 20)
	public String getStatusz() {
		return this.statusz;
	}

	public void setStatusz(String statusz) {
		this.statusz = statusz;
	}

	@Column(name = "KIVAGYBE", length = 1)
	public String getKivagybe() {
		return this.kivagybe;
	}

	public void setKivagybe(String kivagybe) {
		this.kivagybe = kivagybe;
	}

	@Column(name = "NETTO", precision = 20)
	public BigDecimal getNetto() {
		return this.netto;
	}

	public void setNetto(BigDecimal netto) {
		this.netto = netto;
	}

	@Column(name = "BRUTTO", precision = 20)
	public BigDecimal getBrutto() {
		return this.brutto;
	}

	public void setBrutto(BigDecimal brutto) {
		this.brutto = brutto;
	}

	@Column(name = "DNETTO", precision = 20)
	public BigDecimal getDnetto() {
		return this.dnetto;
	}

	public void setDnetto(BigDecimal dnetto) {
		this.dnetto = dnetto;
	}

	@Column(name = "DBRUTTO", precision = 20)
	public BigDecimal getDbrutto() {
		return this.dbrutto;
	}

	public void setDbrutto(BigDecimal dbrutto) {
		this.dbrutto = dbrutto;
	}

	@Column(name = "ALAPBIZT", length = 20)
	public String getAlapbizt() {
		return this.alapbizt;
	}

	public void setAlapbizt(String alapbizt) {
		this.alapbizt = alapbizt;
	}

	@Column(name = "FUVMOD", length = 20)
	public String getFuvmod() {
		return this.fuvmod;
	}

	public void setFuvmod(String fuvmod) {
		this.fuvmod = fuvmod;
	}

	@Column(name = "ATVHELY", length = 20)
	public String getAtvhely() {
		return this.atvhely;
	}

	public void setAtvhely(String atvhely) {
		this.atvhely = atvhely;
	}

	@Column(name = "SIRSZ", length = 4)
	public String getSirsz() {
		return this.sirsz;
	}

	public void setSirsz(String sirsz) {
		this.sirsz = sirsz;
	}

	@Column(name = "SVAROS", length = 25)
	public String getSvaros() {
		return this.svaros;
	}

	public void setSvaros(String svaros) {
		this.svaros = svaros;
	}

	@Column(name = "SCIM", length = 50)
	public String getScim() {
		return this.scim;
	}

	public void setScim(String scim) {
		this.scim = scim;
	}

	@Column(name = "STELEFON", length = 13)
	public String getStelefon() {
		return this.stelefon;
	}

	public void setStelefon(String stelefon) {
		this.stelefon = stelefon;
	}

	@Column(name = "VFAX", length = 13)
	public String getVfax() {
		return this.vfax;
	}

	public void setVfax(String vfax) {
		this.vfax = vfax;
	}

	@Column(name = "SWIFTCODE", length = 15)
	public String getSwiftcode() {
		return this.swiftcode;
	}

	public void setSwiftcode(String swiftcode) {
		this.swiftcode = swiftcode;
	}

	@Column(name = "VORSZAG", length = 30)
	public String getVorszag() {
		return this.vorszag;
	}

	public void setVorszag(String vorszag) {
		this.vorszag = vorszag;
	}

	@Column(name = "VKAPCSTART", length = 30)
	public String getVkapcstart() {
		return this.vkapcstart;
	}

	public void setVkapcstart(String vkapcstart) {
		this.vkapcstart = vkapcstart;
	}

	@Column(name = "MEGRAZON", length = 20)
	public String getMegrazon() {
		return this.megrazon;
	}

	public void setMegrazon(String megrazon) {
		this.megrazon = megrazon;
	}

	// @Column(name = "KOZADOSZAM", length = 20)
	// public String getKozadoszam() {
	// return this.kozadoszam;
	// }
	//
	// public void setKozadoszam(String kozadoszam) {
	// this.kozadoszam = kozadoszam;
	// }

	@Column(name = "UGYINT")
	public Integer getUgyint() {
		return this.ugyint;
	}

	public void setUgyint(Integer ugyint) {
		this.ugyint = ugyint;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "VFIZDAT", length = 19)
	public Date getVfizdat() {
		return this.vfizdat;
	}

	public void setVfizdat(Date vfizdat) {
		this.vfizdat = vfizdat;
	}

	@Column(name = "MEGJFILE")
	public boolean isMegjfile() {
		return this.megjfile;
	}

	public void setMegjfile(boolean megjfile) {
		this.megjfile = megjfile;
	}

	@Column(name = "IBAN", length = 4)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "VKOZADOSZ", length = 20)
	public String getVkozadosz() {
		return this.vkozadosz;
	}

	public void setVkozadosz(String vkozadosz) {
		this.vkozadosz = vkozadosz;
	}

	@Column(name = "NETTOSULY", precision = 17, scale = 3)
	public BigDecimal getNettosuly() {
		return this.nettosuly;
	}

	public void setNettosuly(BigDecimal nettosuly) {
		this.nettosuly = nettosuly;
	}

	@Column(name = "KAMIONJEL", length = 30)
	public String getKamionjel() {
		return this.kamionjel;
	}

	public void setKamionjel(String kamionjel) {
		this.kamionjel = kamionjel;
	}

	@Column(name = "KULREND")
	public boolean isKulrend() {
		return this.kulrend;
	}

	public void setKulrend(boolean kulrend) {
		this.kulrend = kulrend;
	}

	@Column(name = "ESTAT", precision = 8, scale = 0)
	public Integer getEstat() {
		return this.estat;
	}

	public void setEstat(Integer estat) {
		this.estat = estat;
	}

	@Column(name = "IKTATOSZAM", length = 15)
	public String getIktatoszam() {
		return this.iktatoszam;
	}

	public void setIktatoszam(String iktatoszam) {
		this.iktatoszam = iktatoszam;
	}

	@Column(name = "VKAPCSTEL", length = 15)
	public String getVkapcstel() {
		return this.vkapcstel;
	}

	public void setVkapcstel(String vkapcstel) {
		this.vkapcstel = vkapcstel;
	}

	@Column(name = "ELOLEGSSZ", length = 15)
	public String getElolegssz() {
		return this.elolegssz;
	}

	public void setElolegssz(String elolegssz) {
		this.elolegssz = elolegssz;
	}

	@Column(name = "BETUDVA")
	public boolean isBetudva() {
		return this.betudva;
	}

	public void setBetudva(boolean betudva) {
		this.betudva = betudva;
	}

	@Column(name = "ELOLEGERT", precision = 20, scale = 3)
	public BigDecimal getElolegert() {
		return this.elolegert;
	}

	public void setElolegert(BigDecimal elolegert) {
		this.elolegert = elolegert;
	}

	@Column(name = "ISJAVIT")
	public boolean isIsjavit() {
		return this.isjavit;
	}

	public void setIsjavit(boolean isjavit) {
		this.isjavit = isjavit;
	}

	@Column(name = "GARIS")
	public boolean isGaris() {
		return this.garis;
	}

	public void setGaris(boolean garis) {
		this.garis = garis;
	}

	@Column(name = "KGYUB")
	public boolean isKgyub() {
		return this.kgyub;
	}

	public void setKgyub(boolean kgyub) {
		this.kgyub = kgyub;
	}

	@Column(name = "CSERE")
	public boolean isCsere() {
		return this.csere;
	}

	public void setCsere(boolean csere) {
		this.csere = csere;
	}

	@Column(name = "SZAZAS")
	public boolean isSzazas() {
		return this.szazas;
	}

	public void setSzazas(boolean szazas) {
		this.szazas = szazas;
	}

	@Column(name = "BRNDID")
	public Integer getBrndid() {
		return this.brndid;
	}

	public void setBrndid(Integer brndid) {
		this.brndid = brndid;
	}

	@Column(name = "MODKOD")
	public Integer getModkod() {
		return this.modkod;
	}

	public void setModkod(Integer modkod) {
		this.modkod = modkod;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "MODDATUM", length = 19)
	public Date getModdatum() {
		return this.moddatum;
	}

	public void setModdatum(Date moddatum) {
		this.moddatum = moddatum;
	}

	@Column(name = "BEHOZTA")
	public Integer getBehozta() {
		return this.behozta;
	}

	public void setBehozta(Integer behozta) {
		this.behozta = behozta;
	}

	@Column(name = "MINDENOK")
	public boolean isMindenok() {
		return this.mindenok;
	}

	public void setMindenok(boolean mindenok) {
		this.mindenok = mindenok;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "MINDOKDAT", length = 19)
	public Date getMindokdat() {
		return this.mindokdat;
	}

	public void setMindokdat(Date mindokdat) {
		this.mindokdat = mindokdat;
	}

	@Column(name = "LABSZERV")
	public Integer getLabszerv() {
		return this.labszerv;
	}

	public void setLabszerv(Integer labszerv) {
		this.labszerv = labszerv;
	}

	@Column(name = "VENYVONAL", length = 20)
	public String getVenyvonal() {
		return this.venyvonal;
	}

	public void setVenyvonal(String venyvonal) {
		this.venyvonal = venyvonal;
	}

	@Column(name = "AJANLATOT")
	public boolean isAjanlatot() {
		return this.ajanlatot;
	}

	public void setAjanlatot(boolean ajanlatot) {
		this.ajanlatot = ajanlatot;
	}

	@Column(name = "VENYES")
	public boolean isVenyes() {
		return this.venyes;
	}

	public void setVenyes(boolean venyes) {
		this.venyes = venyes;
	}

	@Column(name = "MOREGARI")
	public boolean isMoregari() {
		return this.moregari;
	}

	public void setMoregari(boolean moregari) {
		this.moregari = moregari;
	}

	@Column(name = "JAVKARB")
	public Integer getJavkarb() {
		return this.javkarb;
	}

	public void setJavkarb(Integer javkarb) {
		this.javkarb = javkarb;
	}

	@Column(name = "REKLAMACIO")
	public boolean isReklamacio() {
		return this.reklamacio;
	}

	public void setReklamacio(boolean reklamacio) {
		this.reklamacio = reklamacio;
	}

	// @Temporal(TemporalType.DATE)
	@Column(name = "INSDATUM", length = 19)
	public Date getInsdatum() {
		return this.insdatum;
	}

	public void setInsdatum(Date insdatum) {
		this.insdatum = insdatum;
	}

	@Column(name = "INSKOD")
	public Integer getInskod() {
		return this.inskod;
	}

	public void setInskod(Integer inskod) {
		this.inskod = inskod;
	}

	@Column(name = "MODIZVA")
	public boolean isModizva() {
		return this.modizva;
	}

	public void setModizva(boolean modizva) {
		this.modizva = modizva;
	}

	@Column(name = "KERDESES")
	public boolean isKerdeses() {
		return this.kerdeses;
	}

	public void setKerdeses(boolean kerdeses) {
		this.kerdeses = kerdeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rendel")
	public Set<Rendtet> getRendtets() {
		return this.rendtets;
	}

	public void setRendtets(Set<Rendtet> rendtets) {
		this.rendtets = rendtets;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "KOZADOSZAM")
	public String getKozadoszam() {
		return kozadoszam;
	}

	public void setKozadoszam(String kozadoszam) {
		this.kozadoszam = kozadoszam;
	}

	@Column(name = "DEVIZA")
	public String getDeviza() {
		return deviza;
	}

	public void setDeviza(String deviza) {
		this.deviza = deviza;
	}

	@Column(name = "BNOKOD")
	public String getBnokod() {
		return bnokod;
	}

	public void setBnokod(String bnokod) {
		this.bnokod = bnokod;
	}

	@Column(name = "GYSE_BE")
	public Boolean getGyseBe() {
		return gyseBe;
	}

	public void setGyseBe(Boolean gyseBe) {
		this.gyseBe = gyseBe;
	}

	@Column(name = "DIMENZIO1")
	public Integer getDimenztio1() {
		return dimenztio1;
	}

	public void setDimenztio1(Integer dimenztio1) {
		this.dimenztio1 = dimenztio1;
	}

	@Column(name = "VFELIRDAT")
	public Date getVfelirdat() {
		return vfelirdat;
	}

	public void setVfelirdat(Date vfelirdat) {
		this.vfelirdat = vfelirdat;
	}

	@Column(name = "SNEV")
	public String getSnev() {
		return snev;
	}

	public void setSnev(String snev) {
		this.snev = snev;
	}

	@Column(name = "CSAKUB")
	public Boolean getCsakub() {
		return csakub;
	}

	public void setCsakub(Boolean csakub) {
		this.csakub = csakub;
	}

	@Column(name = "VONALKOD")
	public String getVonalkod() {
		return vonalkod;
	}

	public void setVonalkod(String vonalkod) {
		this.vonalkod = vonalkod;
	}

	@Column(name = "FUVAR")
	public Integer getFuvar() {
		return fuvar;
	}

	public void setFuvar(Integer fuvar) {
		this.fuvar = fuvar;
	}

	@Column(name = "LEFEJTO")
	public Integer getLefejto() {
		return lefejto;
	}

	public void setLefejto(Integer lefejto) {
		this.lefejto = lefejto;
	}

	@Column(name = "SZLAPROFIL")
	public Integer getSzlaprofil() {
		return szlaprofil;
	}

	public void setSzlaprofil(Integer szlaprofil) {
		this.szlaprofil = szlaprofil;
	}

	@Column(name = "LAKOSVEVO")
	public Integer getLakosvevo() {
		return lakosvevo;
	}

	public void setLakosvevo(Integer lakosvevo) {
		this.lakosvevo = lakosvevo;
	}

}
